name: CI

on:
  push:
    branches: [ ftclib ]
  pull_request:
    branches: [ ftclib ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Gradle Build
        run: ./gradlew build -x lint
